
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[542] =
    {   0,
        0,    0,    0,    0,   70,   69,   68,    4,   69,   43,
       69,   69,   69,   43,   61,    5,   47,   48,   46,   67,
       67,   67,   39,   67,   67,   67,   39,   67,   67,   67,
       39,   67,   67,   69,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   43,   69,   68,    0,   57,    0,
       52,    0,   63,    0,   66,   67,   51,   50,   67,   67,
       67,   67,    0,   67,   39,   67,    0,   67,   67,   67,
       67,   67,    0,    0,    0,   65,   67,   67,   67,   67,
       67,   65,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   41,   67,   48,   67,   67,   67,   67,
       67,   67,   67,   53,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   53,    0,    0,   58,
       67,   67,   67,   67,    0,   67,   67,    0,    0,   67,
       67,   67,   67,   67,   67,    0,    0,   56,   43,   67,
       52,   67,    0,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   34,   67,   67,   64,   67,    0,    0,    0,
       67,   67,   67,   67,   67,   67,    0,   67,   67,   25,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,    0,    0,   67,   67,   15,   67,    0,   37,    0,

        7,   67,   67,   67,   67,   44,   67,    0,    0,    0,
        0,   14,   67,    0,   67,   67,   67,   26,   67,   67,
       67,   67,   42,   67,   67,   67,   67,    0,    0,    0,
        0,    0,    0,    0,   67,   67,   67,   67,   67,   32,
        0,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   62,   67,    0,    0,    0,    0,   45,    0,
        0,   67,   67,   67,   67,   55,    0,   60,    0,   67,
        0,   67,   67,   29,   67,   20,   67,   67,    0,   67,
       27,   67,    0,    0,    0,    0,    0,    0,    0,    0,
       67,   67,   67,   67,    0,   67,   67,   67,   33,   67,

       67,   54,   67,   30,   17,    0,   67,    0,    0,   40,
        0,    0,    0,    8,    2,   67,   12,    0,    0,    0,
        0,    0,    0,    0,   48,   67,   67,   67,    0,    0,
       67,   18,   42,    0,    0,    0,    0,    0,    0,    0,
       67,   67,    0,   67,   67,   67,   19,   67,    0,    0,
       28,    0,    0,    0,    0,    0,    2,   67,    0,   59,
        0,    0,    0,    0,   67,    0,   67,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   67,   67,    0,   67,
       67,   67,    0,    0,    0,    0,    0,    0,    0,   67,
        0,    0,    0,    0,    0,   67,    0,    0,   67,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   47,    0,
       16,    0,    0,    0,    0,    0,    0,    0,   13,    3,
       36,    0,    0,   67,    0,    0,   38,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    3,    0,    0,   46,    0,    0,
       22,   21,   41,    0,    0,    0,    0,    0,    0,   11,
        0,    6,    1,    0,   35,    0,    0,    0,    0,    0,
       49,    0,    0,    0,    0,    6,    1,    0,    0,   24,
       23,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   31,    0,    0,    0,    0,    0,
        0,    0,   10,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    9,    0,    0,    0,    0,    0,    0,    0,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,    7,   13,   12,   14,    7,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,    1,   18,
       19,   20,    1,    1,   21,   22,   21,   23,   24,   25,
       21,   21,   26,   21,   27,   28,   21,   29,   30,   31,
       21,   32,   33,   34,   35,   21,   36,   21,   21,   21,
       37,   38,   39,    1,    1,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   21,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   21,
       62,   21,    1,   63,    1,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    4,    4,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    3,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[550] =
    {   0,
        0,    0,    0,    0,  658,  659,   63,  659,   62,  659,
      649,  599,  644,    0,  659,  659,  635,  659,  634,    0,
      608,   25,    0,  611,  646,  601,   46,  588,   57,  603,
       48,   27,  594,   60,   69,   41,  592,   42,   27,   40,
      588,   52,   83,   53,   51,  603,   53,   53,   58,   57,
       75,   72,   70,  598,  578,   72,  130,  124,  659,  130,
      659,  631,  630,  627,  626,    0,  659,  659,  579,  595,
      594,  583,  589,  579,    0,  590,  106,  585,   96,  588,
      568,  568,  128,  132,  136,  659,  582,  567,  580,  566,
      138,    0,  575,  110,  564,  569,   97,  561,  574,  566,

      571,  557,  565,  608,  607,  606,  553,  551,  555,  563,
      555,  553,  599,    0,  111,  545,  116,  542,  560,  116,
      558,  547,  549,  548,  118,  545,  659,  547,  541,  659,
      534,  535,  529,  532,  544,  543,  536,  571,  570,  543,
      524,  522,  528,  535,  530,  148,  150,  659,    0,  524,
        0,  523,  517,  526,  527,  530,  527,  527,  516,  524,
      519,  522,    0,  515,  133,    0,  518,  511,  520,  137,
      515,  503,  500,  499,  499,  512,  497,  497,  505,    0,
      500,  501,  494,  496,  490,  503,  494,  138,  487,  497,
      493,  502,  483,  536,  535,    0,  494,  492,    0,  503,

      659,  478,  494,  477,  483,    0,  481,  176,  184,  188,
      192,    0,  469,  482,  482,  483,  477,    0,  481,  468,
      481,  479,    0,  517,  462,  467,  471,  464,  476,  467,
      459,  457,  146,  461,  467,  452,  452,  458,  459,    0,
      459,  447,  461,  453,  444,  452,  444,  442,  452,  450,
      452,  448,  490,  440,  436,  149,  124,  157,    0,  443,
      476,  445,  436,  435,  482,    0,  194,  659,  196,  481,
      440,  431,  426,    0,  425,    0,  422,  435,  160,  434,
        0,  419,  418,  418,  428,  414,  428,  415,  413,  429,
      412,  420,  413,  411,  420,  415,  418,  417,    0,  416,

      419,    0,  454,    0,    0,  399,  395,  174,  409,  659,
      406,  413,  400,  659,  438,  404,    0,  387,  203,  206,
      209,  213,  186,  444,    0,  389,  442,  397,  391,  385,
      386,    0,  659,  397,  394,  399,  398,  391,  379,  385,
      394,  383,  428,  378,  387,  373,    0,  386,  379,  379,
        0,  383,  380,  366,  373,  377,  659,  370,  366,  659,
      217,  366,  359,  371,  368,  192,  361,  363,  372,  407,
      366,  359,  350,  363,  402,  355,  352,  341,  349,  349,
      396,  341,  341,  353,  338,  339,  347,  334,  349,  347,
      331,  220,  346,  348,  334,  346,  332,  326,  331,  329,

      323,  186,  324,  375,  334,  321,  318,  331,    0,  332,
        0,  331,  368,  367,  326,  305,  324,  326,  362,  240,
      659,  309,  314,  311,  312,  321,    0,  304,  315,  313,
      310,  352,  297,  298,  306,  296,  309,  297,  309,  306,
      291,  289,  292,  286,  659,  285,  292,    0,  288,  282,
      659,  659,  659,  299,  280,  284,  296,  295,  278,  659,
      280,  241,  319,  284,  659,  277,  273,  284,  269,  279,
      659,  273,  267,  271,  270,  659,  659,  277,  259,  659,
      659,  279,  314,  269,  272,  272,  310,  265,  260,  258,
      257,  253,  260,  262,  254,  301,  248,  251,  245,  243,

      241,  253,  245,  293,  659,  248,  243,  277,  237,  248,
      238,  248,  659,  285,  233,  235,  228,  241,  225,  279,
      234,  226,  240,  221,  225,  210,  215,  211,  205,  216,
      249,  211,  659,  200,  183,  182,  233,  163,  121,  114,
      659,  259,  263,   92,  267,   75,  269,  271,  273
    } ;

static yyconst flex_int16_t yy_def[550] =
    {   0,
      541,    1,  542,  542,  541,  541,  541,  541,  543,  541,
      541,  544,  545,  546,  541,  541,  541,  541,  541,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  547,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  541,  541,  541,  543,  541,  541,
      541,  541,  541,  545,  545,  546,  541,  541,  546,  546,
      546,  546,  541,  546,  546,  546,  541,  546,  546,  546,
      546,  546,  547,  541,  541,  541,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  541,  541,  541,  541,
      546,  546,  546,  546,  541,  546,  546,  541,  541,  546,
      546,  546,  546,  546,  546,  548,  541,  541,  546,  546,
      546,  546,  541,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  541,  541,  541,
      546,  546,  546,  546,  546,  546,  541,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  541,  541,  546,  546,  546,  546,  541,  546,  541,

      541,  546,  546,  546,  546,  546,  546,  548,  541,  541,
      541,  546,  546,  541,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  546,  546,  546,  541,  541,  541,
      541,  541,  541,  541,  546,  546,  546,  546,  546,  546,
      541,  546,  546,  546,  546,  546,  546,  546,  546,  546,
      546,  546,  546,  546,  541,  541,  541,  541,  546,  541,
      541,  546,  546,  546,  546,  546,  549,  541,  541,  546,
      541,  546,  546,  546,  546,  546,  546,  546,  541,  546,
      546,  546,  541,  541,  541,  541,  541,  541,  541,  541,
      546,  546,  546,  546,  541,  546,  546,  546,  546,  546,

      546,  546,  546,  546,  546,  541,  546,  541,  541,  541,
      541,  541,  541,  541,  546,  546,  546,  541,  549,  541,
      541,  541,  541,  541,  546,  546,  546,  546,  541,  541,
      546,  546,  541,  541,  541,  541,  541,  541,  541,  541,
      546,  546,  541,  546,  546,  546,  546,  546,  541,  541,
      546,  541,  541,  541,  541,  541,  541,  546,  541,  541,
      541,  541,  541,  541,  546,  541,  546,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  546,  546,  541,  546,
      546,  546,  541,  541,  541,  541,  541,  541,  541,  546,
      541,  541,  541,  541,  541,  546,  541,  541,  546,  541,

      541,  541,  541,  541,  541,  541,  541,  541,  546,  541,
      546,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  546,  541,  541,  546,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  546,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,

      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
        0,  541,  541,  541,  541,  541,  541,  541,  541
    } ;

static yyconst flex_int16_t yy_nxt[724] =
    {   0,
        6,    7,    7,    7,    8,    9,   10,   11,   12,   13,
        6,   14,   15,   16,    6,    6,    6,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   20,   26,   27,   28,
       29,   30,   31,   32,   33,   23,   34,   20,    6,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   20,   44,
       45,   46,   47,   48,   20,   49,   50,   51,   52,   20,
       53,   54,   55,   56,   57,   57,   57,   59,   70,   75,
       77,   75,   86,   80,   84,   85,   98,   66,   99,   72,
       71,   75,   81,   75,   69,   70,   73,  100,   93,   97,
       94,  102,  107,   95,   62,  103,  108,   71,  109,   60,

       74,  117,  115,  110,  113,  116,   78,  119,  114,  111,
      118,   87,   76,  128,  120,  121,  124,  125,   88,  129,
       89,   80,  122,   82,   90,   91,   92,  104,  123,   59,
       81,   57,   57,   57,  105,   58,  138,  141,  139,  106,
      146,  153,  541,  541,  146,  147,   85,   85,  146,  156,
       85,   85,  160,  142,  140,  183,  161,  141,  180,  311,
      189,   60,  209,  210,  211,  211,   68,   58,  157,  178,
      148,  184,  225,  142,  148,  190,  226,  230,  540,  250,
      231,   58,  232,  312,  311,  288,  233,   58,  267,  289,
      541,  541,  309,  234,  154,  251,  267,  269,  210,  210,

      267,  329,  210,  210,  146,  312,  211,  211,  320,  321,
      322,  322,  310,  352,  268,   67,  330,  541,  541,  361,
      321,  321,  268,  321,  321,  267,  268,  322,  322,  362,
      148,  392,  392,  397,  392,  392,  539,  310,  430,  453,
      538,  360,  363,  431,  360,  445,  476,  360,  398,  537,
      536,  268,  535,  445,  476,  534,  533,  532,  360,    6,
        6,    6,    6,   58,  531,   58,   58,   64,  530,   64,
       64,   83,   83,  208,  208,  319,  319,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  511,  510,  509,  508,  507,

      506,  505,  453,  504,  503,  502,  501,  500,  499,  498,
      497,  496,  495,  494,  493,  492,  491,  490,  489,  488,
      487,  486,  485,  484,  483,  482,  453,  481,  480,  479,
      478,  477,  475,  474,  473,  472,  471,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  416,  461,  460,  459,
      458,  375,  457,  432,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  444,  443,  442,  310,  441,
      440,  439,  438,  437,  436,  435,  432,  434,  433,  432,
      429,  428,  427,  426,  425,  424,  423,  422,  421,  420,
      199,  419,  418,  417,  416,  415,  414,  413,  149,  412,

      411,  410,  149,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  396,  395,  394,  393,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  236,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  326,  369,  368,  367,  366,  365,  364,  359,  358,
      357,  356,  355,  354,  353,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  149,  341,  326,  340,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  149,  328,
      327,  326,  325,  324,  323,  318,  317,  316,  315,  314,
      313,  308,  307,  306,  305,  304,  303,   92,  302,  301,

      300,  299,  298,  297,  296,  295,  294,  293,  149,  292,
      291,  290,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  249,  248,  247,  246,  245,
      244,  243,  242,  149,  241,  240,  239,  238,  237,  236,
      235,  229,  228,  227,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  188,  187,  186,  185,  182,

      181,  179,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  159,  158,
      155,  152,  151,  150,  149,  145,  144,  143,  140,  137,
      136,  135,  134,  133,  132,  131,   65,   65,  130,  130,
      127,  126,  112,  101,   96,   82,   79,   76,   74,   73,
       72,   69,   68,   67,   65,   63,   61,  541,    5,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,

      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541
    } ;

static yyconst flex_int16_t yy_chk[724] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    9,   22,   27,
       29,   31,   35,   32,   34,   34,   39,  546,   39,   40,
       22,   27,   32,   31,   36,   38,   43,   40,   36,   38,
       36,   42,   44,   36,  544,   42,   44,   38,   45,    9,

       44,   49,   48,   45,   47,   48,   29,   50,   47,   45,
       49,   35,   47,   56,   50,   50,   53,   53,   35,   56,
       35,   51,   51,   52,   35,   35,   35,   43,   52,   58,
       51,   57,   57,   57,   43,   60,   77,   79,   77,   43,
       83,   91,   83,   83,   84,   84,   84,   84,   85,   94,
       85,   85,   97,   79,  115,  120,   97,  117,  117,  257,
      125,   58,  146,  146,  147,  147,  540,   60,   94,  115,
       84,  120,  165,  117,   85,  125,  165,  170,  539,  188,
      170,   60,  170,  258,  257,  233,  170,   60,  208,  233,
      208,  208,  256,  170,   91,  188,  209,  209,  209,  209,

      210,  279,  210,  210,  211,  258,  211,  211,  267,  267,
      269,  269,  256,  308,  208,  538,  279,  319,  319,  320,
      320,  320,  209,  321,  321,  322,  210,  322,  322,  323,
      211,  361,  361,  366,  392,  392,  537,  308,  402,  536,
      535,  319,  323,  402,  320,  420,  462,  321,  366,  534,
      532,  322,  531,  420,  462,  530,  529,  528,  392,  542,
      542,  542,  542,  543,  527,  543,  543,  545,  526,  545,
      545,  547,  547,  548,  548,  549,  549,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  512,
      511,  510,  509,  508,  507,  506,  504,  503,  502,  501,

      500,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  479,
      478,  475,  474,  473,  472,  470,  469,  468,  467,  466,
      464,  463,  461,  459,  458,  457,  456,  455,  454,  450,
      449,  447,  446,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      426,  425,  424,  423,  422,  419,  418,  417,  416,  415,
      414,  413,  412,  410,  408,  407,  406,  405,  404,  403,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,

      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  365,  364,  363,  362,  359,  358,
      356,  355,  354,  353,  352,  350,  349,  348,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  331,  330,  329,  328,  327,  326,  324,  318,  316,
      315,  313,  312,  311,  309,  307,  306,  303,  301,  300,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  280,  278,  277,
      275,  273,  272,  271,  270,  265,  264,  263,  262,  261,
      260,  255,  254,  253,  252,  251,  250,  249,  248,  247,

      246,  245,  244,  243,  242,  241,  239,  238,  237,  236,
      235,  234,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  222,  221,  220,  219,  217,  216,  215,  214,  213,
      207,  205,  204,  203,  202,  200,  198,  197,  195,  194,
      193,  192,  191,  190,  189,  187,  186,  185,  184,  183,
      182,  181,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  169,  168,  167,  164,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  150,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  129,  128,  126,  124,  123,  122,  121,  119,

      118,  116,  113,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  103,  102,  101,  100,   99,   98,   96,   95,
       93,   90,   89,   88,   87,   82,   81,   80,   78,   76,
       74,   73,   72,   71,   70,   69,   65,   64,   63,   62,
       55,   54,   46,   41,   37,   33,   30,   28,   26,   25,
       24,   21,   19,   17,   13,   12,   11,    5,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,

      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  541
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ps.l"
#line 2 "ps.l"
	#include <string>
	#include <iostream>
	#include "y.tab.h"
	using namespace std;
	int commentLevel = 0;

/*Definitions of Some Basic Tokens */
#line 807 "lex.yy.c"

#define INITIAL 0
#define IN_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 20 "ps.l"


#line 998 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 542 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 659 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "ps.l"
{printf("<MAIN>"); return MAIN;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "ps.l"
{printf("<BEGIN_OF_BLOCK>"); return BEGIN_OF_BLOCK;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "ps.l"
{printf("<END_OF_BLOCK>"); return END_OF_BLOCK;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "ps.l"
{printf("<END_OF_PRGM>"); return END_OF_PRGM;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "ps.l"
{printf("<END_OF_INPUT>"); return END_OF_INPUT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "ps.l"
{printf("<END_OF_MAIN>"); return END_OF_MAIN;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "ps.l"
{printf("<FUNCTION>"); return FUNCTION;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "ps.l"
{printf("<USR_DEF_SHAPE>"); return USR_DEF_SHAPE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "ps.l"
{printf("<FUNCT_NAME>"); return FUNCT_NAME;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "ps.l"
{printf("<END_OF_DEF>"); return END_OF_DEF;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "ps.l"
{printf("<INHERITANCE>"); return INHERITANCE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "ps.l"
{printf("<RETURN>"); return RETURN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "ps.l"
{printf("<USR_SHAPE_NAME>"); return USR_SHAPE_NAME;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "ps.l"
{printf("<PARAM_DELIM>"); return PARAM_DELIM;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "ps.l"
{printf("<DRAW>"); return DRAW;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "ps.l"
{printf("<POSITION>"); return POSITION;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "ps.l"
{printf("<WIDTH>"); return WIDTH;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "ps.l"
{printf("<HEIGHT>"); return HEIGHT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "ps.l"
{printf("<STROKE>"); return STROKE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "ps.l"
{printf("<COLOR>"); return COLOR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "ps.l"
{printf("<FILL_STATE>"); return FILL_STATE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "ps.l"
{printf("<FILL_COLOR>"); return FILL_COLOR;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "ps.l"
{printf("<BORDR_STATE>"); return BORDR_STATE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "ps.l"
{printf("<BORDR_COLR>"); return BORDR_COLR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "ps.l"
{printf("<RED>"); return RED;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "ps.l"
{printf("<BLUE>"); return BLUE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "ps.l"
{printf("<GREEN>"); return GREEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "ps.l"
{printf("<YELLOW>"); return YELLOW;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "ps.l"
{printf("<BLACK>"); return BLACK;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "ps.l"
{printf("<WHITE>"); return WHITE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "ps.l"
{printf("<RND_CRNRS>"); return RND_CRNRS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "ps.l"
{printf("<NAME>"); return NAME;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "ps.l"
{printf("<START>"); return  START;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "ps.l"
{printf("<END>"); return END;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "ps.l"
{printf("<ARROW_STRT>"); return ARROW_STRT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "ps.l"
{printf("<ARROW_END>"); return ARROW_END;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "ps.l"
{printf("<SHAPE>"); return SHAPE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "ps.l"
{printf("<DIR>"); return DIR;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "ps.l"
{printf("<DIR_VAL>"); return DIR_VAL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "ps.l"
{printf("<TYPECAST>"); return TYPECAST;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "ps.l"
{printf("<IF>"); return IF;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "ps.l"
{printf("<ELSE>"); return ELSE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "ps.l"
{printf("<OP>"); return OP;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "ps.l"
{printf("<TRUE>"); return TRUE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "ps.l"
{printf("<FALSE>"); return FALSE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "ps.l"
{printf("<GRTR>"); return GRTR;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "ps.l"
{printf("<LESS>"); return LESS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "ps.l"
{printf("<ASSIGNMENT>"); return ASSIGNMENT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "ps.l"
{printf("<LOG_EQ>"); return LOG_EQ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "ps.l"
{printf("<GRTR_EQ>"); return GRTR_EQ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "ps.l"
{printf("<LESS_EQ>"); return LESS_EQ;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "ps.l"
{printf("<AND>"); return AND;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "ps.l"
{printf("<OR>"); return OR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "ps.l"
{printf("<FOR>"); return FOR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "ps.l"
{printf("<WHILE>"); return WHILE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "ps.l"
{printf("<NUM>"); return NUM;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "ps.l"
{printf("<STRING>"); return STRING;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "ps.l"
{printf("<CHAR>"); return CHAR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "ps.l"
{printf("<RGB>"); return RGB;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "ps.l"
{printf("<POS_X_POS_Y>"); return POS_X_POS_Y;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "ps.l"
{printf("<PARAMETER>"); return PARAMETER;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "ps.l"
{printf("<USR_DEF_PARAM>"); return USR_DEF_PARAM;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "ps.l"
{printf("<ACCESS>"); return ACCESS;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "ps.l"
{printf("<USR_DEF_VAR>"); return USR_DEF_VAR;}
	YY_BREAK
case 65:
#line 87 "ps.l"
case 66:
YY_RULE_SETUP
#line 87 "ps.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "ps.l"
{printf("<ID>"); return ID;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 89 "ps.l"
;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 91 "ps.l"
ECHO;
	YY_BREAK
#line 1424 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 542 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 542 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 541);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 91 "ps.l"


int yywrap(void) {
  return 1;
}

